repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0 # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
- repo: https://github.com/ambv/black
  rev: '25.1.0'
  hooks:
  - id: black
