version: '3'

volumes:
  pg_data: { }

services:
  postgres:
    image: "postgres:13.1-alpine"
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - pgsql-env

  lemur:
    # image: "netlix-lemur:latest"
    restart: on-failure
    build:
      context: ../
      dockerfile: docker/Dockerfile-src
    depends_on:
      - postgres
      - redis
    env_file:
      - lemur-env
      - pgsql-env
    ports:
      - 87:80
      - 447:443

  redis:
    image: "redis:alpine3.12"
    restart: on-failure
